BEGIN TRANSACTION;

-- Insert Counties
INSERT INTO Counties (Id, Code, Name) VALUES (1, 30, 'Baringo');
INSERT INTO Counties (Id, Code, Name) VALUES (2, 36, 'Bomet');
INSERT INTO Counties (Id, Code, Name) VALUES (3, 39, 'Bungoma');
INSERT INTO Counties (Id, Code, Name) VALUES (4, 40, 'Busia');
INSERT INTO Counties (Id, Code, Name) VALUES (5, 28, 'Elgeyo-Marakwet');
INSERT INTO Counties (Id, Code, Name) VALUES (6, 14, 'Embu');
INSERT INTO Counties (Id, Code, Name) VALUES (7, 7, 'Garissa');
INSERT INTO Counties (Id, Code, Name) VALUES (8, 43, 'Homa Bay');
INSERT INTO Counties (Id, Code, Name) VALUES (9, 11, 'Isiolo');
INSERT INTO Counties (Id, Code, Name) VALUES (10, 34, 'Kajiado');
INSERT INTO Counties (Id, Code, Name) VALUES (11, 37, 'Kakamega');
INSERT INTO Counties (Id, Code, Name) VALUES (12, 35, 'Kericho');
INSERT INTO Counties (Id, Code, Name) VALUES (13, 22, 'Kiambu');
INSERT INTO Counties (Id, Code, Name) VALUES (14, 3, 'Kilifi');
INSERT INTO Counties (Id, Code, Name) VALUES (15, 20, 'Kirinyaga');
INSERT INTO Counties (Id, Code, Name) VALUES (16, 45, 'Kisii');
INSERT INTO Counties (Id, Code, Name) VALUES (17, 42, 'Kisumu');
INSERT INTO Counties (Id, Code, Name) VALUES (18, 15, 'Kitui');
INSERT INTO Counties (Id, Code, Name) VALUES (19, 2, 'Kwale');
INSERT INTO Counties (Id, Code, Name) VALUES (20, 31, 'Laikipia');
INSERT INTO Counties (Id, Code, Name) VALUES (21, 5, 'Lamu');
INSERT INTO Counties (Id, Code, Name) VALUES (22, 16, 'Machakos');
INSERT INTO Counties (Id, Code, Name) VALUES (23, 17, 'Makueni');
INSERT INTO Counties (Id, Code, Name) VALUES (24, 9, 'Mandera');
INSERT INTO Counties (Id, Code, Name) VALUES (25, 10, 'Marsabit');
INSERT INTO Counties (Id, Code, Name) VALUES (26, 12, 'Meru');
INSERT INTO Counties (Id, Code, Name) VALUES (27, 44, 'Migori');
INSERT INTO Counties (Id, Code, Name) VALUES (28, 1, 'Mombasa');
INSERT INTO Counties (Id, Code, Name) VALUES (29, 21, 'Murang''a');
INSERT INTO Counties (Id, Code, Name) VALUES (30, 47, 'Nairobi');
INSERT INTO Counties (Id, Code, Name) VALUES (31, 32, 'Nakuru');
INSERT INTO Counties (Id, Code, Name) VALUES (32, 29, 'Nandi');
INSERT INTO Counties (Id, Code, Name) VALUES (33, 33, 'Narok');
INSERT INTO Counties (Id, Code, Name) VALUES (34, 46, 'Nyamira');
INSERT INTO Counties (Id, Code, Name) VALUES (35, 18, 'Nyandarua');
INSERT INTO Counties (Id, Code, Name) VALUES (36, 19, 'Nyeri');
INSERT INTO Counties (Id, Code, Name) VALUES (37, 25, 'Samburu');
INSERT INTO Counties (Id, Code, Name) VALUES (38, 41, 'Siaya');
INSERT INTO Counties (Id, Code, Name) VALUES (39, 6, 'Taita-Taveta');
INSERT INTO Counties (Id, Code, Name) VALUES (40, 4, 'Tana River');
INSERT INTO Counties (Id, Code, Name) VALUES (41, 13, 'Tharaka-Nithi');
INSERT INTO Counties (Id, Code, Name) VALUES (42, 26, 'Trans-Nzoia');
INSERT INTO Counties (Id, Code, Name) VALUES (43, 23, 'Turkana');
INSERT INTO Counties (Id, Code, Name) VALUES (44, 27, 'Uasin Gishu');
INSERT INTO Counties (Id, Code, Name) VALUES (45, 38, 'Vihiga');
INSERT INTO Counties (Id, Code, Name) VALUES (46, 8, 'Wajir');
INSERT INTO Counties (Id, Code, Name) VALUES (47, 24, 'West Pokot');

-- Insert SubCounties
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (1, NULL, 'Baringo central', 1);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (2, NULL, 'Baringo north', 1);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (3, NULL, 'Baringo south', 1);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (4, NULL, 'Eldama ravine', 1);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (5, NULL, 'Mogotio', 1);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (6, NULL, 'Tiaty', 1);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (7, NULL, 'Bomet central', 2);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (8, NULL, 'Bomet east', 2);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (9, NULL, 'Chepalungu', 2);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (10, NULL, 'Konoin', 2);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (11, NULL, 'Sotik', 2);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (12, NULL, 'Bumula', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (13, NULL, 'Kabuchai', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (14, NULL, 'Kanduyi', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (15, NULL, 'Kimilil', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (16, NULL, 'Mt Elgon', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (17, NULL, 'Sirisia', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (18, NULL, 'Tongaren', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (19, NULL, 'Webuye east', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (20, NULL, 'Webuye west', 3);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (21, NULL, 'Budalangi', 4);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (22, NULL, 'Butula', 4);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (23, NULL, 'Funyula', 4);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (24, NULL, 'Nambele', 4);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (25, NULL, 'Teso North', 4);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (26, NULL, 'Teso South', 4);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (27, NULL, 'Keiyo north', 5);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (28, NULL, 'Keiyo south', 5);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (29, NULL, 'Marakwet east', 5);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (30, NULL, 'Marakwet west', 5);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (31, NULL, 'Manyatta', 6);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (32, NULL, 'Mbeere north', 6);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (33, NULL, 'Mbeere south', 6);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (34, NULL, 'Runyenjes', 6);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (35, NULL, 'Daadab', 7);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (36, NULL, 'Fafi', 7);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (37, NULL, 'Garissa', 7);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (38, NULL, 'Hulugho', 7);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (39, NULL, 'Ijara', 7);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (40, NULL, 'Lagdera balambala', 7);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (41, NULL, 'Homabay town', 8);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (42, NULL, 'Kabondo', 8);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (43, NULL, 'Karachwonyo', 8);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (44, NULL, 'Kasipul', 8);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (45, NULL, 'Mbita', 8);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (46, NULL, 'Ndhiwa', 8);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (47, NULL, 'Rangwe', 8);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (48, NULL, 'Suba', 8);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (49, NULL, 'Central', 9);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (50, NULL, 'Garba tula', 9);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (51, NULL, 'Kina', 9);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (52, NULL, 'Merit', 9);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (53, NULL, 'Oldonyiro', 9);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (54, NULL, 'Sericho', 9);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (55, NULL, 'Isinya.', 10);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (56, NULL, 'Kajiado Central.', 10);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (57, NULL, 'Kajiado North.', 10);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (58, NULL, 'Loitokitok.', 10);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (59, NULL, 'Mashuuru.', 10);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (60, NULL, 'Butere', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (61, NULL, 'Kakamega central', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (62, NULL, 'Kakamega east', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (63, NULL, 'Kakamega north', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (64, NULL, 'Kakamega south', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (65, NULL, 'Khwisero', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (66, NULL, 'Lugari', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (67, NULL, 'Lukuyani', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (68, NULL, 'Lurambi', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (69, NULL, 'Matete', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (70, NULL, 'Mumias', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (71, NULL, 'Mutungu', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (72, NULL, 'Navakholo', 11);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (73, NULL, 'Ainamoi', 12);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (74, NULL, 'Belgut', 12);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (75, NULL, 'Bureti', 12);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (76, NULL, 'Kipkelion east', 12);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (77, NULL, 'Kipkelion west', 12);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (78, NULL, 'Soin sigowet', 12);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (79, NULL, 'Gatundu north', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (80, NULL, 'Gatundu south', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (81, NULL, 'Githunguri', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (82, NULL, 'Juja', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (83, NULL, 'Kabete', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (84, NULL, 'Kiambaa', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (85, NULL, 'Kiambu', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (86, NULL, 'Kikuyu', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (87, NULL, 'Limuru', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (88, NULL, 'Ruiru', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (89, NULL, 'Thika town', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (90, NULL, 'lari', 13);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (91, NULL, 'Genzw', 14);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (92, NULL, 'Kaloleni', 14);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (93, NULL, 'Kilifi north', 14);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (94, NULL, 'Kilifi south', 14);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (95, NULL, 'Magarini', 14);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (96, NULL, 'Malindi', 14);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (97, NULL, 'Rabai', 14);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (98, NULL, 'Kirinyaga central', 15);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (99, NULL, 'Kirinyaga east', 15);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (100, NULL, 'Kirinyaga west', 15);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (101, NULL, 'Mwea east', 15);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (102, NULL, 'Mwea west', 15);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (103, NULL, 'Kisumu central', 17);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (104, NULL, 'Kisumu east', 17);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (105, NULL, 'Kisumu west', 17);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (106, NULL, 'Mohoroni', 17);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (107, NULL, 'Nyakach', 17);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (108, NULL, 'Nyando', 17);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (109, NULL, 'Seme', 17);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (110, NULL, 'Ikutha', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (111, NULL, 'Katulani', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (112, NULL, 'Kisasi', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (113, NULL, 'Kitui central', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (114, NULL, 'Kitui west', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (115, NULL, 'Lower yatta', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (116, NULL, 'Matiyani', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (117, NULL, 'Migwani', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (118, NULL, 'Mutitu', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (119, NULL, 'Mutomo', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (120, NULL, 'Muumonikyusu', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (121, NULL, 'Mwingi central', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (122, NULL, 'Mwingi east', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (123, NULL, 'Nzambani', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (124, NULL, 'Tseikuru', 18);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (125, NULL, 'Kinango', 19);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (126, NULL, 'Lungalunga', 19);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (127, NULL, 'Msambweni', 19);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (128, NULL, 'Mutuga', 19);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (129, NULL, 'Laikipia central', 20);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (130, NULL, 'Laikipia east', 20);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (131, NULL, 'Laikipia north', 20);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (132, NULL, 'Laikipia west', 20);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (133, NULL, 'Nyahururu', 20);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (134, NULL, 'Lamu East', 21);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (135, NULL, 'Lamu West', 21);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (136, NULL, 'Kathiani', 22);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (137, NULL, 'Machakos town', 22);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (138, NULL, 'Masinga', 22);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (139, NULL, 'Matungulu', 22);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (140, NULL, 'Mavoko', 22);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (141, NULL, 'Mwala', 22);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (142, NULL, 'Yatta', 22);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (143, NULL, 'Kaiti', 23);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (144, NULL, 'Kibwei west', 23);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (145, NULL, 'Kibwezi east', 23);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (146, NULL, 'Kilome', 23);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (147, NULL, 'Makueni', 23);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (148, NULL, 'Mbooni', 23);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (149, NULL, 'Banissa', 24);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (150, NULL, 'Lafey', 24);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (151, NULL, 'Mandera East', 24);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (152, NULL, 'Mandera North', 24);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (153, NULL, 'Mandera South', 24);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (154, NULL, 'Mandera West', 24);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (155, NULL, 'Laisamis', 25);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (156, NULL, 'Moyale', 25);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (157, NULL, 'North hor', 25);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (158, NULL, 'Saku', 25);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (159, NULL, 'Buuri', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (160, NULL, 'Igembe central', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (161, NULL, 'Igembe north', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (162, NULL, 'Igembe south', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (163, NULL, 'Imenti central', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (164, NULL, 'Imenti north', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (165, NULL, 'Imenti south', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (166, NULL, 'Tigania east', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (167, NULL, 'Tigania west', 26);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (168, NULL, 'Awendo', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (169, NULL, 'Kuria east', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (170, NULL, 'Kuria west', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (171, NULL, 'Mabera', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (172, NULL, 'Ntimaru', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (173, NULL, 'Rongo', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (174, NULL, 'Suna east', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (175, NULL, 'Suna west', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (176, NULL, 'Uriri', 27);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (177, NULL, 'Changamwe', 28);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (178, NULL, 'Jomvu', 28);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (179, NULL, 'Kisauni', 28);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (180, NULL, 'Likoni', 28);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (181, NULL, 'Mvita', 28);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (182, NULL, 'Nyali', 28);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (183, NULL, 'Gatanga', 29);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (184, NULL, 'Kahuro', 29);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (185, NULL, 'Kandara', 29);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (186, NULL, 'Kangema', 29);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (187, NULL, 'Kigumo', 29);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (188, NULL, 'Kiharu', 29);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (189, NULL, 'Mathioya', 29);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (190, NULL, 'Murang’a south', 29);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (191, NULL, 'Dagoretti North Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (192, NULL, 'Dagoretti South Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (193, NULL, 'Embakasi Central Sub Count', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (194, NULL, 'Embakasi East Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (195, NULL, 'Embakasi North Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (196, NULL, 'Embakasi South Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (197, NULL, 'Embakasi West Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (198, NULL, 'Kamukunji Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (199, NULL, 'Kasarani Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (200, NULL, 'Kibra Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (201, NULL, 'Lang''ata Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (202, NULL, 'Makadara Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (203, NULL, 'Mathare Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (204, NULL, 'Roysambu Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (205, NULL, 'Ruaraka Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (206, NULL, 'Starehe Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (207, NULL, 'Westlands Sub County', 30);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (208, NULL, 'Bahati', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (209, NULL, 'Gilgil', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (210, NULL, 'Kuresoi north', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (211, NULL, 'Kuresoi south', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (212, NULL, 'Molo', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (213, NULL, 'Naivasha', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (214, NULL, 'Nakuru town east', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (215, NULL, 'Nakuru town west', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (216, NULL, 'Njoro', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (217, NULL, 'Rongai', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (218, NULL, 'Subukia', 31);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (219, NULL, 'Aldai', 32);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (220, NULL, 'Chesumei', 32);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (221, NULL, 'Emgwen', 32);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (222, NULL, 'Mosop', 32);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (223, NULL, 'Namdi hills', 32);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (224, NULL, 'Tindiret', 32);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (225, NULL, 'Narok east', 33);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (226, NULL, 'Narok north', 33);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (227, NULL, 'Narok south', 33);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (228, NULL, 'Narok west', 33);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (229, NULL, 'Transmara east', 33);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (230, NULL, 'Transmara west', 33);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (231, NULL, 'Borabu', 34);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (232, NULL, 'Manga', 34);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (233, NULL, 'Masaba north', 34);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (234, NULL, 'Nyamira north', 34);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (235, NULL, 'Nyamira south', 34);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (236, NULL, 'Kinangop', 35);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (237, NULL, 'Kipipiri', 35);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (238, NULL, 'Ndaragwa', 35);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (239, NULL, 'Ol Kalou', 35);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (240, NULL, 'Ol joro orok', 35);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (241, NULL, 'Kieni east', 36);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (242, NULL, 'Kieni west', 36);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (243, NULL, 'Mathira east', 36);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (244, NULL, 'Mathira west', 36);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (245, NULL, 'Mkurweni', 36);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (246, NULL, 'Nyeri town', 36);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (247, NULL, 'Othaya', 36);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (248, NULL, 'Tetu', 36);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (249, NULL, 'Samburu east', 37);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (250, NULL, 'Samburu north', 37);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (251, NULL, 'Samburu west', 37);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (252, NULL, 'Alego usonga', 38);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (253, NULL, 'Bondo', 38);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (254, NULL, 'Gem', 38);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (255, NULL, 'Rarieda', 38);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (256, NULL, 'Ugenya', 38);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (257, NULL, 'Unguja', 38);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (258, NULL, 'Mwatate', 39);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (259, NULL, 'Taveta', 39);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (260, NULL, 'Voi', 39);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (261, NULL, 'Wundanyi', 39);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (262, NULL, 'Bura', 40);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (263, NULL, 'Galole', 40);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (264, NULL, 'Garsen', 40);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (265, NULL, 'Chuka', 41);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (266, NULL, 'Igambangobe', 41);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (267, NULL, 'Maara', 41);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (268, NULL, 'Muthambi', 41);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (269, NULL, 'Tharak north', 41);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (270, NULL, 'Tharaka south', 41);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (271, NULL, 'Cherangany', 42);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (272, NULL, 'Endebess', 42);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (273, NULL, 'Kiminini', 42);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (274, NULL, 'Kwanza', 42);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (275, NULL, 'Saboti', 42);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (276, NULL, 'Loima', 43);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (277, NULL, 'Turkana central', 43);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (278, NULL, 'Turkana east', 43);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (279, NULL, 'Turkana north', 43);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (280, NULL, 'Turkana south', 43);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (281, NULL, 'Ainabkoi', 44);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (282, NULL, 'Kapseret', 44);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (283, NULL, 'Kesses', 44);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (284, NULL, 'Moiben', 44);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (285, NULL, 'Soy', 44);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (286, NULL, 'Turbo', 44);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (287, NULL, 'Emuhaya', 45);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (288, NULL, 'Hamisi', 45);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (289, NULL, 'Luanda', 45);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (290, NULL, 'Sabatia', 45);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (291, NULL, 'vihiga', 45);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (292, NULL, 'Eldas', 46);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (293, NULL, 'Tarbaj', 46);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (294, NULL, 'Wajir East', 46);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (295, NULL, 'Wajir North', 46);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (296, NULL, 'Wajir South', 46);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (297, NULL, 'Wajir West', 46);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (298, NULL, 'Central Pokot', 47);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (299, NULL, 'North Pokot', 47);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (300, NULL, 'Pokot South', 47);
INSERT INTO SubCounties (Id, Code, Name, CountyId) VALUES (301, NULL, 'West Pokot', 47);

COMMIT;